// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orgxiugqbqacdhneyrxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZ3hpdWdxYnFhY2RobmV5cnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTA5OTAsImV4cCI6MjA3MzUyNjk5MH0._65dXA9cf-Iszs2Vc_r-s4TfXk15NgLo_QL7Mm2H62Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});